# Generated by Django 5.2.4 on 2025-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time_posted', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scraped_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
