# Generated by Django 5.2.4 on 2025-08-04 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraped_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='scraped_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
